---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: yes

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Copy over the standard aliases file
  template: src=../templates/standard-aliases.sh dest=/etc/profile.d

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Create Docker directory
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"

- name: Create app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/portainer"

- name: Suppress login messages
  ansible.builtin.file:
    name: /home/{{ username }}/.hushlogin
    mode: "0644"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve