---
username: "<username>"

docker_dir: /opt/homelab/docker_apps
data_dir: /opt/homelab/data

puid: "<puid>"

pgid: "<pgid>"

server_name: "<server_name>"

domain: "<domain_name>"

cloudflare_email: "<cloudflare_email>"

cloudflare_api_key: "<cloudflare_api_key>"

traefik_basic_auth_hash: "<traefik_basic_auth_hash>"

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin